### ISSUE TITLE
[Discussion] How to present TII information inside the GUI?

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#282]
This issue is to discuss how to present the TII information inside the GUI.

At the moment the TII is only printed into the standard output.
![1533728290217blob](https://user-images.githubusercontent.com/11171787/43900261-9afe3580-9be4-11e8-9e6a-847073c45813.jpg)

**Comment by mpbraendli** [comment]
Currently, the information can change quite often, and false TII comb pattern pairs can show up in the list if the receiver is running for a longer duration. This has to be fixed because the measurement algorithm is missing a good quality criterion.

It would be nice to display this TII information alongside the CIR, maybe even on the same plot. I don't know if it's easy to find out which CIR peak corresponds to which TII, which would be the nicest way to display.

**Comment by AlbrechtL** [comment]
Do you mean to display the text inside the plot? Can you provide a simple mockup?

**Comment by mpbraendli** [comment]
Here's a mockup with a base picture from welle-cli, but the idea is the same

![cir_mockup](https://user-images.githubusercontent.com/5902825/45021193-3393a400-b031-11e8-93c9-4a296c010851.png)

The green bars correspond to where we think the TII is relative to the CIR graph. Wide bars mean there is less confidence. The number next to it is mainId:subId.

But before we can do this, we need

* a better working confidence indication
* calculate absolute delays relative to start of NULL symbol (or start of PRS) and align this with the CIR calculation

What do you think about such a representation?

**Comment by AlbrechtL** [comment]
> What do you think about such a representation?

It looks great! But I don't know how difficult the graphic implementation is.

**Comment by AlbrechtL** [comment]
To add the TII information to the CIR is not really complicated (https://github.com/AlbrechtL/welle.io/issues/309) as long we know at which sample which information needs to be shown. Is this information is available?

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
