### ISSUE TITLE
Mono stations only play out of one channel

### ISSUE THREAD

**Issue by jay-to-the-dee** [AlbrechtL/welle.io#316]
This is a low priority feature enhancement more than anything.

Unfortunately in the UK a lot of commercial DAB stations are not only using the old inefficient MP2 codec, but are also broadcast in Mono only. When selecting such a station, the audio comes out of only one of my speakers which makes it sound much quieter than the full stereo stations. Is it possible to duplicate the mono audio stream across both left and right channels to remove this effect?

Cheers,

**Comment by AlbrechtL** [comment]
Interesting. This mono on both speakers was working in previous versions. Which version did you use?

**Comment by andimik** [comment]
Yes, confirmed. Mono plays on left channel only. Using latest commit.

**Comment by mpbraendli** [comment]
@basicmaster how is dablin handling DAB-mono? Does it upconvert it to stereo internally?

Before commit a8391cb we had code in `Mp2Processor::PutAudio` that converted mono to stereo, maybe that changed.

**Comment by basicmaster** [comment]
In case of MP2, the decoded stream is forwarded without channel count conversion i.e. a mono MP2 station results in a single audio channel. So in the mono MP2 station case, the `StartAudio` callback is called with `channels` set to 1.

Note that `channels` here does not necessarilly correspond to the actual channel count, as the (alternate) FDK AAC decoder unfortunately outputs stereo for mono channels, too. The reason is that this decoder assumes that PS could be present...

**Comment by AlbrechtL** [comment]
I think we have to put new conversation code to `void DecoderAdapter::PutAudio(const uint8_t *data, size_t len)` to do the conversation to two channels.
https://github.com/AlbrechtL/welle.io/blob/6ddf226b8efadb9a30e1585ebd07b66f8aa08108/src/backend/decoder_adapter.cpp#L92-L118

**Comment by AlbrechtL** [comment]
@basicmaster Thanks for fixing!

**Comment by jay-to-the-dee** [comment]
Can confirmed fixed. Thanks everyone!
