### ISSUE TITLE
DAB rtl_tcp server sharing 

### ISSUE THREAD

**Issue by iuliandj** [AlbrechtL/welle.io#326]
Hello,
Is anyone interested in sharing DAB servers from his town ?
I have a rtl_tcp server with raspberry pi for DAB and FM band (curently no DAB signal on my area, just on propagation, but with FM band signal), powered 24 h per day, in Romania.
If someone is interested in sharing servers with rtl_tcp to decode with Welle.io please let me know by an e-mail at: iuliandj01@gmail.com

Thank you ! 

Regards,
Iulian

**Comment by basicmaster** [comment]
You may have a look at http://www.dabmonitor.de/ (though this page doesn't make use of rtl_tcp).

**Comment by andimik** [comment]
Why not sharing the eti?

**Comment by iuliandj** [comment]
The project from http://www.dabmonitor.de/ is not about rtl_tcp servers witch you can connect to.

**Comment by andimik** [comment]
I fear welle-cli will not satisfy you.

The best solution is using raw files you can find on some pages.

**Comment by mpbraendli** [comment]
> Thank you AlbrechtL. I took a look at welle-cli. It can be use as a client, under windows 7 ?

I don't know if compiling welle-cli for windows works, but you can install it on a linux machine (PC or Raspi 3), and connect to the integrated webserver with any browser, and listen to the radio through the browser over the network.

**Comment by andimik** [comment]
But I find the idea interesting.

For some time now I have been trying to send a (recorded) rawfile to port 1234.

The reason is that I want to use Andreas Gsinn's great DAB player (Windows) which does not have a file input, but can handle rtltcp on port 1234.

So, if Welle.io would be able to stream the raw data to the network this would be great.

**Comment by mpbraendli** [comment]
@andimik I must admit I don't understand your scenario, and I don't really see what welle.io has to do with your goal of getting a raw IQ file into Gsinn's DAB player's `rtltcp` interface.

I would propose to close this issue because:

1. it's not really an issue about the implementation, it's a question
2. we have discussed an alternative approach (welle-cli remote web-based receiver)

@iuliandj It's an interesting idea, thanks for sharing!

**Comment by AlbrechtL** [comment]
> I don't know if compiling welle-cli for windows works,

It works. The welle-cli for windows comes with welle-io windows version. You will find welle-cli.exe inside the installation directory.

**Comment by AlbrechtL** [comment]
I'm closing it because of inactivity.
