### ISSUE TITLE
[macOS] Create DMG image

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#442]
welle.io runs also on macOS but it is not easy to compile and install it specifically for non experts.

It would be really nice to have a DMG to run welle.io.
Qt has also a deploy tool for macOS (https://doc.qt.io/archives/qt-5.11/osx-deployment.html).

The Linux AppImage is build with Travis CI. Luckily Travis support also macOS (https://docs.travis-ci.com/user/reference/osx/). So it is possible to create the DMG automatically like the Windows installer and the Linux AppImage.

@tenzap Are you interested in creating a DMG image?

**Comment by tenzap** [comment]
If I understand well, according to this discussion [comment17](https://trac.macports.org/ticket/59779#comment:17), it seems welle.io cannot be distributed as binary on macOS because of licensing issues : one file of mpg123 (`./src/libout123/modules/coreaudio.c`), probably used for audio output on macos, is licensed under strict GPLv2.

**Comment by AlbrechtL** [comment]
The `libout123` is only used for welle-cli but not for the GUI. If we distribute only the GUI variant there should be not problem.
