### ISSUE TITLE
[question] increasing to "unstable samplerate" and apply decimation

### ISSUE THREAD

**Issue by skinkie** [AlbrechtL/welle.io#606]
I would like to know if anyone already tried to increase the samplerate 2.88M/s - 3.2 M/s, and apply decimation of 2 in order to get a better signal noise ratio, and reduce the effect of strong neigbouring channels. I could have obviously also rephrased my question in a way, as: has anyone reduced the INPUT_RATE to 1600000 (or is that an issue for frequency correction?)

I have changed the code and noticed that 1600000, 1800000, 1900000, 2248000 gives SyncOnPhase failed (which surprises me a bit), so I am asking this question.

**Comment by mpbraendli** [comment]
I strongly suspect that the default 2048000 sample rate is assumed by a few parts of the demodulator, which is why you cannot just change it. The fact that SyncOnPhase fails is probably a consequence.
One approach would be to oversample (depends on your device capabilities) and then filter and decimate to 2048000, otherwise one could track all these places where welle.io implicitly assumes 2048ksps and rework those.
I believe this would work best with integer multiples of 2048ksps, because you'd want to adapt the FFT size (from 2048 to 4096) and then discard the unused FFT bins.
