### ISSUE TITLE
[rtl_tcp, Android rtl_sdr] AGC failed for strong signals

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#68]
The original rtlsdr AGC doesn't work for strong signals. The AGC has to be implemented inside the driver. Maybe use the AGC code from the rtl_sdr input (8b4648f).

**Comment by zmark17** [comment]
Is that the reason that welle.io for Android no longer works with AGC since I put antenna amplifier on DAB antenna?
On weak signal it finished scanning successfully and played DAB stations, but with amplifier (and AGC on) - no signal, no scanning (stucks at 5B or 5C) and no playing sound. SNR without amp was around 8 dB, now is perhaps 15 dB. 
When AGC is switched off and gain set manually around 30-40 everything seems to work fine.

**Comment by AlbrechtL** [comment]
This sounds like this issue.

**Comment by AlbrechtL** [comment]
Fixed in 2e77b53. Will be included in the next release.
