### ISSUE TITLE
Homebrew: welle.io depends on soapysdr, but then disables it?

### ISSUE THREAD

**Issue by micolous** [AlbrechtL/welle.io#685]
The Homebrew package for `welle.io` has an explicit dependency on `soapysdr` and `soapyuhd` for #346:

https://github.com/AlbrechtL/welle.io/blob/66675c9a4160c644a5ade5bf7a0cd0647647f33c/HomebrewFormula/welle.io.rb#L20-L21

But then it appears to be disabled in the build process as of https://github.com/AlbrechtL/welle.io/commit/6a4ca089b7503d80c36c5573b894f856bba65047 (#645)

https://github.com/AlbrechtL/welle.io/blob/66675c9a4160c644a5ade5bf7a0cd0647647f33c/HomebrewFormula/welle.io.rb#L27

The supported hardware list for the project seems to indicate that this dependency is optional: https://github.com/AlbrechtL/welle.io#soapysdr-notes

Given that using SoapySDR requires users add yet-another Homebrew tap, IMO a better option here would be [to put this behind an `option` flag](https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies).

**Comment by AlbrechtL** [comment]
Thanks for reporting!

@mitchblank Can you have a look at it?

**Comment by mitchblank** [comment]
I'll try to take a look soon... I'm in the middle of moving house this week so won't have much time in the next few days.

SoapyUHD has it's own problems with homebrew on my machine but I haven't had a chance to look into at all.

**Comment by AlbrechtL** [comment]
Thanks for looking into it - take your time.

**Comment by orryverducci** [comment]
> SoapyUHD has it's own problems with homebrew on my machine but I haven't had a chance to look into at all.

I've just discovered when installing SoapyUHD via Homebrew on macOS Monterey it fails to build and install, but that's been fixed in the master branch, so if you install via brew using the `--HEAD` option it should work. Not sure if that's the issue you've had @mitchblank?

This will definitely need to be put in to the Homebrew formula to ensure it installs on updated systems, at least until a new release of SoapyUHD comes out.
