### ISSUE TITLE
[Gui, Linux] on 2.4, some icons are missing

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#713]
Still the same as here https://github.com/AlbrechtL/welle.io/commit/1c1b7b8bcf8f7792adf5248c040dc2655c4d7e74 with 2.4. I didn't have such a problem with 2.3.

This is with the downloaded appimage on debian bullseye (latest, up-to-date stable), Qt 5.15.2. Style= the default one, but all are touched.

**Comment by AlbrechtL** [comment]
I can't reproduce your issue. Maybe it is something with your graphic card driver?

**Comment by tenzap** [comment]
If it were, icon would be missing in 2.3 also, right? (which is not the case)

**Comment by tenzap** [comment]
What about adding both path in that commit?

**Comment by AlbrechtL** [comment]
The issue is that I don't understand what the problem is. The new path is the correct once. Why in your case only the wrong path is working I don't have any idea.

**Comment by andimik** [comment]
Could you share a screenshot?

**Comment by tenzap** [comment]
Screenshot is in https://github.com/AlbrechtL/welle.io/commit/1c1b7b8bcf8f7792adf5248c040dc2655c4d7e74

**Comment by AlbrechtL** [comment]
@tenzap PR #723 is merge. Can you confirm the fix, please?

**Comment by purewasa** [comment]
Hi @AlbrechtL,

I am running version 2.4 since April 2022 on Rapsberry Pi OS bullseye.
Everything works. Some qml warnings, but no serious problems.
Suddenly, icons were missing. Like in:
https://github.com/AlbrechtL/welle.io/commit/1c1b7b8bcf8f7792adf5248c040dc2655c4d7e74
Must be by an update. (I update once/twice a week.)
Icons were there something before 2022-11-07.
The only major thing I can remeber is a kernel update to:
$ uname -a
Linux raspberrypi 5.15.76-v7+ #1597 SMP Fri Nov 4 12:13:17 GMT 2022 armv7l GNU/Linux

From this issue I tried commit:
https://github.com/dforsi/welle.io/commit/e1784abe8a7fd4f0b35ac15819217276fa25d9b6
to fix the problem, which is in branch next.
Cherry-picking this commit to master of 2022-11-13 (2.4 + 4 commits)
fixes the problem! (I don't have Qt6 installed!)

Kind regards,

purewasa
