### ISSUE TITLE
Favourite stations

### ISSUE THREAD

**Issue by sierragls** [AlbrechtL/welle.io#732]
It it possible to save favourite stations? This will save having to scroll all the way to find the station I want to listen to on android car stereo.

**Comment by andimik** [comment]
Yes, like in a browser just press the asterisk icon.

**Comment by sierragls** [comment]
Can this be done on android? I haven’t seen an asterisk. Tried holding my finger on the station but nothing.

**Comment by andimik** [comment]
You just need to click on the icon. Then it will become yellow instead of white. 

But I confirm that there is a bug.

The favorite list stays empty on Android. I have never tested it before.

![Screenshot_20220519-100807](https://user-images.githubusercontent.com/24510556/169245668-722ebbfc-bd69-4f5c-8580-fac838e0748a.png)
![Screenshot_20220519-100814](https://user-images.githubusercontent.com/24510556/169245688-3293c1a3-71c8-4757-94a5-4332b6cf0326.png)

**Comment by sierragls** [comment]
Mine is different to that. There is no star. 


![60B62351-69DD-4B2C-A0EF-2C7665C0D451](https://user-images.githubusercontent.com/103198278/169258424-e4cae652-e1d8-47cd-bdad-5abe87e17171.jpeg)
 
![97BCBC2A-DDAB-4C57-B5C1-075E9DFB348B](https://user-images.githubusercontent.com/103198278/169258400-ead011fe-3ac1-43bf-b581-542886543ba5.jpeg)

**Comment by sierragls** [comment]
Got it now I had an older version  downloaded it, you are right favourites don’t work. 

There is another issue when i minimise the app to do something else the signal goes so the app has to be constantly on screen for it to work, are there any settings to change this?
