### ISSUE TITLE
Github Action for Raspberry Pi builds

### ISSUE THREAD

**Issue by MoJo2600** [AlbrechtL/welle.io#781]
I created a Dockerfile to compile welle.io for Raspberry Pi on my x86 machine. I thought I could go a step further and create a github action for it as well, as it is pretty straight forward.

Current state:
* The build works and produces a binary (See: [https://github.com/MoJo2600/welle.io/actions/runs/4957542506](https://github.com/MoJo2600/welle.io/actions/runs/4957542506)
* Currently the generated build output is stored as an artifact, but there is no further processing / releasing
* I did not test the binary yet

Not sure if somebody is interessed in this or if you want to integrate it into the welle.io repository. If not, just close this issue / pull request.

**Comment by AlbrechtL** [comment]
Thanks for the Dockerfile idea! Can you explain the use case a bit?

**Comment by AlbrechtL** [comment]
Currently, I disabled the raspberry build because the generated docker image is not easy to use. One improvement could be to upload it to docker hub. But the use case is still not clear to me. Especially on Raspberry OS you can install welle.io via `apt install welle.io`.

For now I'm closing this issue.
