### ISSUE TITLE
No sound with DAC installed even when piping audio to aplay

### ISSUE THREAD

**Issue by alan-de-windt** [AlbrechtL/welle.io#786]
How can I set where welle.io and welle-cli send the audio?  

I have an Audiophonics DAC on my Pi4 which is listed as snd_rpi_hifiberry_dac but I not able to get any sound from either welle.io or welle.cli.  I have tried piping the sound to aplay like this:

welle-io | /usr/bin/aplay -D "SoftVolume" -r 48000 -f S16_LE -t raw -c 2

This pipe works very well with other RTL-SDR players, also no issues with VLC when selecting "SoftVolume" as the audio device.

Note that I am getting the following on the 3rd line of the terminal when I start welle.io, with or without the above piping:

 "Audio: Current sound output "auto_null" 

...which does not look good. 

Someone please help if they know how to get this working as otherwise it seems to be working very well listing all of my DAB stations in the UI with good reception, etc.

**Comment by AlbrechtL** [comment]
Thanks for your report.
1. welle.io doesn't support audio pipes. So piping can't work
2. welle.io always uses the system's default audio device. Since 2017 (https://github.com/AlbrechtL/welle.io/issues/116) there is an open issue for a selectable audio device. Maybe in a further version we will have that.

For now I'm closing this issue.
